# Generated by Django 6.0.5 on 2026-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_image_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('new', 'Yangi ovqat'), ('leftover', 'Qolgan ovqat')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='food',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
